style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/krydus/emeraldai/go-emerald-app
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - config
        - chrore
        - docs
        - style
        - lint
        - test
        - BREAKING CHANGE
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
